name: 'greencar'
version: '1.0'
config-version: 2

profile: 'greencar_local'

model-paths: ['models']
target-path: 'target'
clean-targets: ['target', 'dbt_packages']

models:
  greencar:
    bronze:
      +materialized: view
    silver:
      +materialized: view
    gold:
      +materialized: table
