FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY config/ ./config/
COPY dbt/ ./dbt/
COPY scripts/ ./scripts/

CMD ["python", "scripts/run_dbt_job.py"]
